---
- name: redeploy k8s
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  tasks:
    - name: Ansible fact - ansible_date_time
      debug:
      var: ansible_date_time
    - name: Executar redeploy
      block:
        - name: Para deployment
          k8s_json_patch:
            kind: Deployment
            namespace: default
            name: nginx-deployment
            patch:
              - op: replace
                path: /spec/template/metadata/annotations
                # value: {'kubectl.kubernetes.io/restartedAt':'2022-01-07T14:12:00-03:00'}
                # value: {"kubectl.kubernetes.io/restartedAt":"{{ lookup('pipe','date +%Y:%m:%dT%H:%M:%S') }}-03:00"}
                value: {"kubectl.kubernetes.io/restartedAt": " {{ ansible_date_time.iso8601 }} "}
          register: result
        - debug:
            var: result
        - set_fact: 
            add_info: "AWX:DATA:SUCCESS= Execução de redeploy com sucesso."
        - debug:
            msg: 
              - "{{ add_info }}"
        - set_fact:
            state: 'true'    
      rescue:
        - set_fact:
            msg_result: "AWX:ERROR:MSG= Execução de redeploy com erro"
        - fail:
            msg: "{{ msg_result }}"
            
        - set_fact:
            state: 'false'
