---
- name: redeploy k8s
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  tasks:
    - debug: msg="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}-03:00"
    - name: Executar redeploy
      block:
        - name: Para deployment
          k8s_json_patch:
            kind: Deployment
            namespace: default
            name: nginx-deployment
            patch:
              - op: replace
                path: /spec/template/metadata/annotations
                value: {"kubectl.kubernetes.io/restartedAt":"{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}-03:00"}
          register: result
        - debug:
            var: result
        - set_fact: 
            add_info: "AWX:DATA:SUCCESS= Execução de redeploy com sucesso."
        - debug:
            msg: 
              - "{{ add_info }}"
        - set_fact:
            state: 'true'    
      rescue:
        - set_fact:
            msg_result: "AWX:ERROR:MSG= Execução de redeploy com erro"
        - fail:
            msg: "{{ msg_result }}"
            
        - set_fact:
            state: 'false'
