---
- name: test k8s
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  tasks:
  - name: Create a k8s namespace
    k8s:
      name: awx
      api_version: v1
      kind: Namespace
      state: present
